dataset: 'data/input/orebro.gfs.log'

prob_occ: 0.75

laser:
  max_range: 5

map:
  size: [100, 100]
  resolution: 15

plot:
  liveplot_speed: 0.01 # Live plot speed
  gif_speedup: 1000 
  lidar_alpha: 0.4 # Transperancy
  lidar_color: 'r' # Red
  robot_color: 'g' # Green
  plot_output_filename: 'data/output/occupancy_plot.pdf'